### ISSUE TITLE
Fork해서 이용할 경우, 빌드가 필요해 보입니다.

### ISSUE THREAD

**Issue by taegon** [jmbyun/jmbyun.github.io#1]
안녕하세요. 좋은 자료 공유해주셔서 감사합니다.
fork해서 이용해보니 어렵지 않게 금방 멋진 페이지를 만들 수 있네요.

다만, 제가 적용하면서 몇가지 수정한 부분이 있어서 글로 남깁니다. README에 업데이트되면 좋을 것 같습니다.

1. config.js를 수정하더라도, 빌드를 새로 하지 않으면, 이미 빌드된 dist 폴더 안에 이전 값이 저장되어 있어서 반영이 되지 않았습니다. 저는 빌드를 하지 않고, dist 폴더 내에서 해당 키와 doc id 를 찾아서 수정하였습니다. 조금 품이 들겠지만, GitHub Actions를 이용하면 좋을 것 같습니다. 사용자 입장에서는 로컬에 개발환경을 구축하지 않아도 손쉽게 쓸 수 있으니까요. 빌드가 꼭 필요하다면, 빌드 과정을 README에 포함해주시면 좋겠습니다.
1. username.github.io를 가정하고 구성하셨는데, 저 같은 경우, 이미 기본 페이지는 다른 용도를 쓰고 있어서, https://username.github.io/project-name 와 같이 이용하였습니다. 이 경우, 소스 코드에서 `/dist/...`로 javascript 등을 참조 하고 있어서 https://username.github.io/project-name/dist가 아닌 https://username.github.io/dist에서 리소스를 찾게 되더군요. 이 역시 빌드된 index.html에서 해당 부분을 찾아서 수정하였습니다. `/dist/...`로 시작하는 절대 경로 부분을 상대 경로인 `./dist/...`로 수정하여 해결하였습니다. 그리고 font같은 경우에는 상대경로로 바꾸니 `https://username.github.io/dist/dist/asset`과 같이 `dist`가 중복되더군요. 절대 경로일때는 문제가 없을텐데 상대경로로 하니, 중복되어서, font를 가져다 쓰는 부분은 `/dist/assets/...` 대신 `./assets/...`로 수정하였습니다.
1. 마지막으로 google API에서 키를 등록하고, google sheets에서 sharing를 하는 부분을 첨부해주신 링크를 참조하여 어렵지 않게 따라할 수 있었습니다. 하지만, 중간중간 설명이 부족한 부분이 있어서 바쁜 대학원생들이 따라하기 위해서는 조금 더 정리를 해서 README에 포함되면 좋을 것 같습니다.

SNS에서 대학원생이거나 연구원 신분으로 지내시는 분들께 개인 홈페이지를 권하는 것을 심심찮게 봅니다. 저도 그 필요성을 느끼고 있구요. 물론 마크다운이나 간단한 html 코드로 작성해도 되지만, 이렇게 구글 docs으로 컨텐츠를 관리할 수 있도록 제공하는 툴이 갖는 강점이 매우 크다고 생각됩니다. 앞으로 100스타, 1000스타 받으시고, 많은 대학원생들이 이용하면 좋겠습니다.

**Comment by taegon** [comment]
GitHub actions으로 배포부분을 붙여 보았습니다.
https://github.com/taegon/academic-website-actions
POI 버전이 9.0일 때, 의존성 있는 모듈 중 보안이슈가 있는 것들이 있어서, POI 12.x로 올렸는데, 올리는 과정에서 이런저런 수정을 했습니다.  참고로, GitHub Actions를 이용하시면, 빌드하면서 패키지를 검색해서 보안이슈가 있는 버전을 알려줍니다.

**Comment by jmbyun** [comment]
좋은 의견과 contribution 감사합니다. 일단 `config.js` 파일은 빌드할때 번들에 함께 포함하지 않고 클라이언트에서 따로 가져오도록 수정해서 말씀하신 "fork해서 이용할 경우 빌드가 필요한 문제" 해결해 두었습니다. :)
